### ISSUE TITLE
tree node labels are displayed incorrectly on MacSafari

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#172]
tree node labels are displayed incorrectly on MacSafari. See below:
![brunel_treediagram_macsafari_nodetextbug](https://cloud.githubusercontent.com/assets/21226717/19698147/b04c7c46-9ab3-11e6-9d25-8fbde4494025.png)

**Comment by grahamwills** [comment]
Added a fix for some label issues in safari; fixed something similar -- hopefully will fix this!

**Comment by cjiang-ibm** [comment]
The problem still exists with latest Brunel 2.2 build from master branch.
![image](https://cloud.githubusercontent.com/assets/21226717/22339327/32f51e34-e3af-11e6-938d-9e894736465d.png)

**Comment by grahamwills** [comment]
I believe these have been fixed in 2.3

**Comment by dpierucci** [comment]
This issue appears to still exist. Please use the following syntax and data to reproduce:

bar x(UniqueCarrier) y(#count) sort(#count) tooltip(#all)


[airline3krows.csv.txt](https://github.com/Brunel-Visualization/Brunel/files/1312077/airline3krows.csv.txt)

**Comment by kevin-sorat** [comment]
I have seen this issue in the pie chart on Safari
![image](https://user-images.githubusercontent.com/2375191/30865360-578e029c-a2a4-11e7-8144-31ba2c7dfe67.png)

**Comment by grahamwills** [comment]
I am having difficulty replicating these issues. It would be helpful if at least the Brunel script that generated the pie and the tree were included. I can probably mock up some data if that cannot be posted, but I do need the brunel

**Comment by kevin-sorat** [comment]
@grahamwills - Here is the brunel syntax for the pie and the data

:
bar y(#count) stack polar color(UniqueCarrier) sort(#count) label(UniqueCarrier, ' (', #count, '%)') tooltip(#all) percent(#count) legends(none)

**Comment by kevin-sorat** [comment]
[airline3krows.csv.zip](https://github.com/Brunel-Visualization/Brunel/files/1369820/airline3krows.csv.zip)

**Comment by grahamwills** [comment]
@cjiang-ibm are you still seeing this with the latest build? I cannot reproduce the pie chart issue and don't have the data for the tree

**Comment by cjiang-ibm** [comment]
I'm still seeing the issue. You can try this: 
https://model-viewer-dev.stage1.mybluemix.net/mdlvr/assets/html/testbed_v3.html

![image](https://user-images.githubusercontent.com/21226717/33078655-fc19018e-ce98-11e7-8b2b-6cec057e07f9.png)

**Comment by grahamwills** [comment]
Inspecting the generated SVG, it looks correct and as expected. When I go to the site I see that a number of styles have been applied, one of which is a `white-space:pre-wrap` option. This is not supported fully on SVG and seems to be the cause of the issue. I recommend modifying that style to fix the issue.

I am closing it, as it is a CSS/SVG style issue, not Brunel
