### ISSUE TITLE
Still there --- Transposed Bar chart: some bars overlap axis when viewed in FireFox and macOS Safari

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#189]
Some bars overlap axis when viewed in FireFox. With Chrome, it worked as expected.

FixFox:
 
![image](https://cloud.githubusercontent.com/assets/21226717/21905047/a8a6919c-d8cb-11e6-8c79-958088a416fd.png)

I'm attaching the html file here. 
[LECanvasTest.zip](https://github.com/Brunel-Visualization/Brunel/files/702683/LECanvasTest.zip)

**Comment by grahamwills** [comment]
Looking at the included Brunel javascript file, it does not have the changes we added to support a div that is originally hidden, and only loaded later. With the latest version of the code, this issue should be fixed.

The root cause was that when initially laying out the chart, it did not know its size because the div was hidden (which gives it a result size of zero). This has been fixed in the JS to get the width and height values directly if the observed sizes are zero.

**Comment by cjiang-ibm** [comment]
With latest Brunel 2.2 (latest codes from master branch), we are still seeing the same problem.
And additional to FireFox, the same problem happens on macOS Safari.
