### ISSUE TITLE
Spark Dataframe Scala - Magic brunel failed to execute with error:  org/brunel/scala/Brunel$.cacheData(Ljava/lang/String;Lorg/apache/spark/sql/Dataset;)V

### ISSUE THREAD

**Issue by charles2588** [Brunel-Visualization/Brunel#217]
When trying to visualize spark dataframe with spark 2.0 and scala 2.11 with brunel magic.
It fails and throw
Spark Dataframe Scala - Magic brunel failed to execute with error:  org/brunel/scala/Brunel$.cacheData(Ljava/lang/String;Lorg/apache/spark/sql/Dataset;)V

17/03/08 17:23:41 WARN toree.magic.MagicManager: Magic brunel failed to execute with error: 
org/brunel/scala/Brunel$.cacheData(Ljava/lang/String;Lorg/apache/spark/sql/Dataset;)V
res11: Either[org.apache.toree.magic.CellMagicOutput,org.apache.toree.magic.LineMagicOutput] =
Left(Map(text/plain -> Magic brunel failed to execute with error:
org/brunel/scala/Brunel$.cacheData(Ljava/lang/String;Lorg/apache/spark/sql/Dataset;)V))
17/03/08 17:23:41 WARN v5.stream.KernelOutputStream: Suppressing empty output: ''

Reproduce Environment:-
Scala 2.11 spark 2.0 Jupyter Notebook 4.2.0(Python 2.7.11 (default, Jun 24 2016, 12:41:03) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] Apache Toree)

%%brunel data('car10') x(origin) y(horsepower) mean(horsepower) bar tooltip(#all) :: width=300, height=300

Installed brunel magic using
%Addjar --magic https://brunelvis.org/jar/spark-kernel-brunel-all-2.3.jar -f

**Comment by danrope** [comment]
Hello,

Is this happening on IBM Datascience Experience?

**Comment by charles2588** [comment]
@danrope 
Yes it is happening on IBM [DSX](http://datascience.ibm.com/).

**Comment by kartha01** [comment]
I am running into the same issue on IBM DSX using the baseball.csv data

**Comment by castanan** [comment]
I have the same issue trying to run brunel on IBM DSX with Scala 2.11 spark 2.0

**Comment by danrope** [comment]
The issue was within DSX and my understanding is that it is now resolved.  I suggest trying again to use Brunel 2.3 in your notebook.

`%AddJar -magic https://brunelvis.org/jar/spark-kernel-brunel-all-2.3.jar -f `

**Comment by alokkumar70** [comment]
Hi for me the problem remains.

Code - %AddJar -magic https://brunelvis.org/jar/spark-kernel-brunel-all-2.3.jar -f

Starting download from https://brunelvis.org/jar/spark-kernel-brunel-all-2.3.jar

Magic AddJar failed to execute with error: 
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
